rules:
  array-bracket-spacing:
  - error
  - never
  no-trailing-spaces:
  - error
  - skipBlankLines: true
  dot-notation:
  - error
  - allowKeywords: true
  eqeqeq:
  - error
  - always
  - 'null': never
  eol-last: error
  brace-style:
  - error
  - 1tbs
  - allowSingleLine: true
  indent:
  - error
  - tab
  - SwitchCase: 1
  semi:
  - error
  - always
  semi-spacing:
  - error
  - after: true
    before: false
  no-multi-spaces: error
  space-before-function-paren:
  - error
  - never
  quotes:
  - error
  - double
  - avoidEscape: true